[phases.setup]
nixPkgs = ['python3', 'gcc']

[phases.install]
cmds = ['python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt']

[phases.build]
cmds = []

[start]
cmd = 'python main.py'

[build]
buildFlags = ["--load"]  # Важный флаг для сохранения образа
