[build]
buildImage = true
saveImage = true
provider = "nixpacks"

[phases]
setup = { nixPkgs = ["python3", "gcc"] }
install = { cmds = ["python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"] }

[start]
cmd = "python main.py"
